image:
  repository: asia-south1-docker.pkg.dev/zepto-with-gitops/prod-repo/zepto-backend
  tag: 53c4a9df4c73f38db6df8ef63aed7cca1961329c
  pullPolicy: IfNotPresent

replicaCount: 3

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

resources:
  requests:
    cpu: 150m
    memory: 200Mi
  limits:
    cpu: 500m
    memory: 400Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 15
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 75

rollingUpdate:
  maxUnavailable: 1
  maxSurge: 1

probes:
  readiness:
    path: /readyz
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3

  liveness:
    path: /healthz
    initialDelaySeconds: 15
    periodSeconds: 20
    timeoutSeconds: 2
    failureThreshold: 3

  startup:
    path: /healthz
    periodSeconds: 5
    failureThreshold: 30

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

serviceAccount:
  create: true
  name: backend-sa

envSecretName: zepto-backend-secret