# EXAMPLE ONLY — replace encryptedData with real `kubeseal` output.
# Once sealed, this file is 100% safe to store in Git.
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zepto-db-secret
  namespace: zepto
spec:
  encryptedData:
    mysql-root-password: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEQ...   # kubeseal output
    mysql-password: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEQ...
  template:
    metadata:
      name: zepto-db-secret
      namespace: zepto
    type: Opaque
