---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: zepto-db-secret
  namespace: zepto
spec:
  encryptedData:
    mysql-password: AgCOaXzB9SAF3Cc4UkR6m8DERRNqckMd/fmBJLIdPRJ7fuTA/PV92yIbEb0hr6n1cMc7hnWOzGtlMTNlvMaeA1tnzoScszZPhRLXbU3L7KJJjrS+7KV0GGc9A4WGI1HRgT8gvq5duHpYTMamXvtRgkDEshpjOP0fA56pOCsAWdPM7SpBeIpiO+q1iOK9LZAOmDIRXM2axmxyI0j2aEIQySHmacoSxetdRPs3YD70QislcZwJ3wP0m120dBGIRdpRdZluFxaDwrUvBvR9YiWBFJucCgxMyokF3yLSc+DWIk6oE2Y0dJcnGnzfkRoufYT5XgJ1p4yDCAO6pwKQHx70JkTAcgFCje9oMua5nfHsKomfrXAIJNFj5DbNaVTQgjhtkgQezi99KePXPnq5h1n7XDwh8lBXaI5OgY2eGPg8e090SvgbPLIlnxwfsktAgRoynIvaZ7j1MqKMmnLMwvVS4QEj7UaVxjAMFArBdEKl3BVrVa7JcmJxWr6oIHDz4Y2BSk2IEK14RfDrb92/KKDZMeUWQRUoIlDyrqhayKxRe83W0bwH+6RJBIduogprkQWhB3MAbsj/Hha65EKIZnDTPIAWyrK4SKky2kqufxt9NU51edlRlinxzh3Zqxo2QNmpmUaIg9dl56TP8lRZjkAj7BQkIAbBZIZ1eMg1wSBcGdoonKy/KIpSVIuAfpNt0JXIOStEXlBCwogBQmW1j2JzYL+lHWugWusFIjQ=
    mysql-root-password: AgCZRUD6wGTorQJCRup9+fdDywq429bmONhqfeuA5Op+9p4Odaf7vkKdaDumAIENpuAgEeqMnoqokiL/uReY9uGk+FJYoSbmZ5Pk2+5d+PmpUdtAx2WFhmlPoXxRThmU7FpARpcqSrLuyLRjwNXDBaLp+bM66yvlFT1hqla5YEGw5y2ATdOsm8Vwcfy8yTzXCAjzH2aV6oeGF9jPRIWsERcnyxsrhpciszScwxy78bqCY4F0fEcH5aK1sccbtgmhTijlqRvS1kS/f8Yv0p60Qs0IrQyOwP/gnZ9KkBE5GNiF3XhHj7IOi70gQRu4vsrXDnjHOk0XzJx9cSQ3e6UXvCssNvwFAexYGH6Hv9KG+U/F/iMWEhreJDxg1G3wrgn9sZUIwHmsjbBBWT7WrTZOzQbWj5o+FPiMmzISSqP9AcibmyEGxiQzUIwnFN2g32x5Da/6pbkIMol7O/JlskPj9JoLKDZUoM+RoEszshUr+JtLxJ0R3sTagZ6+xDyy88jXBOQJTCPQp3TaQLeyytbnw3gYNQ0aKgcgnfdvLzoLVJfyS3EwvfiGC8xQBVVeLB5FrTpYX0dOml4m9wcLfFfdULQi7TbW3kVMPE5yS2v4nF/Tf3O8JQZ4i3WbRIzo9YyvbxYEVW0wp0j69ftSyi2DHu48lKqRn7WyFt2dwXjQC+WXvxBvrGwTrE91a9DZoUArWqV88di4WPqJ98sjhtLGHGG0YQMSmOFGotc=
  template:
    metadata:
      creationTimestamp: null
      name: zepto-db-secret
      namespace: zepto
