apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zepto-backend-secret
  namespace: zepto
spec:
  encryptedData:
    DB_PASSWORD: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEQ...   # kubeseal output
    JWT_SECRET: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEQ...
    API_KEY: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEQ...
  template:
    metadata:
      name: zepto-backend-secret
      namespace: zepto
    type: Opaque
