---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: zepto-db-secret
  namespace: zepto
spec:
  encryptedData:
    mysql-password: AgB6x992aEFKoaaRqzUC9T3LQKUmYjGO8nDke0RcalFRLlx6ZRqLCpzcajK51e0v+WhtUSC33nKvBH9oFb1piOifG4dPZAJU9GkPoB8xgjLs6/gWK9DN1QnjkrP674w9is1s3jHgc1Py3f1Jn76hh896s8QgxEK8OxX9DdGLbzzyMYycNWTFqyoemHRnMWF06e1uZ47Naj8hzs8kaHPGQP01AyF58usc++NkxM/Eempegcn6nuvJu6x10kPjq+3Eh4AF4uRHGWNVMwC8i0/IuPiGssTCFZ9viW/3rLsLLYovcfL92FUqgB/wKGV546SkRS7WdUz8w43vYPtjx860jSxhrgbtssCQ+OMOVnGXcklafgM1BEqYNXrfINLpujpL/YY9sz0QnunvLjsjUc5EY0GDFmEyrPtm7BSg2hSqHqrKKiR4ATjUKBiXm5V4jkGhCxQfhrA/xSllLikIQDpyDi3vbPd6RdlrC3j6UJoeotVUkqcFw5EfjiKNj5rtPHcuBELx+6RpCp75ILwjbPjgBCY9tAu3E0nJvVoVvtFMHum1acVmcIi6Z6gdEsoUf/vDh3ehsMQQkTdSGGntYySZW+6h+Pnk/rEvUW6iLZLj93DU2HkTgvmHA6QUjVLz69wdwCY6lV9Wcw4DjvJ0Vtk+lKd1K51JryT3adUsfLo2SSIdyoL4P5XTAogtL6lWzI3qwVeprXZZtPzwfPDQZDNa6LNarXrUOQLCctI=
    mysql-root-password: AgCG8skqwMyomOR7yuiYO+wrswwEzRgtayKI/ttuiPJka2giXZP9LyTFiD/d8d5iIFt0M5lzSSl0hUq1M7YsuIr/lrCXqtIS/mG2JxiG0Eo2xA6HubfZ5uih6v5AFt4neH0Bs6HLmxpyQKtVLeaEn8s9RQz53WIo5ErojwX0tNBll7YNCP2eeYzIoIRQcu6uyr4tynL08+adZb1GBqyI7l72g2DXknAU8OrTsaX65wLGA9Jk34BOx+LrxYfyCsI0cxkwzT1kotU2h6Wa536c8VXr0hjMNJzQuwTDUd2tiYSVc8b1sICCiIYPov7LpYSvRJoMOpo7VbVx+mJqjuiVOFp/RIPT64ZNSc/EzQFZRQKBpSvQhM6hbSCoV1O6uYnhlV+ktIDzjBU9or6QuEgAM6a6YRNCPHImhmej6hTCSzrUKdRYlR4MZog29EIeRCg+pyIoFzxD49TyIgTKa7Td+IB/cYxiHm3akAX6KwCuj1aq/i7BYOeqkVMFmrY1dg2xueSrwOmH128ezDaCfbm9wQZb+o4ZtLZmiPfnTx70AgwrLAIdAYllQaVO30m+uhDjTZfufHnQdZz65T9w2wl0IEFAJRwlnRhIHDcgpXofDc0HXP9ff/3LYCYjWw5wpYLKmmN9Au7pCDjqdii3mFWfzz8bemWgOTPxeYeYXujLgyLJhdwucsvA9GmEWE6vFkXGHaoqoyVDIcygoGgWgKH2yvP+VmWgFmwL6ORBTOf7zYlzRMjydI/OPeH8CsEGMA==
  template:
    metadata:
      creationTimestamp: null
      name: zepto-db-secret
      namespace: zepto
