---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: zepto-db-secret
  namespace: zepto
spec:
  encryptedData:
    mysql-password: AgCIYaswo0rD50YlV4NpnFuIAT5xjt0sQYOWdjGu6zTmcyzaShnJ1dsRSD9aulKW8dWlBDJPfshQssi59o6Yz0F4xp5cGFoYYSm6gBqpB8SpRnpc+HQ7SHIBWTNa2iTNMEJ/Pho6kn1RlSPFJ4HKy+0hAWHWZUn0gbAWErJGWKA0G2GRY2NKpEybgKvsA50Y4AiyH3Imdd52sCFIKLkCXiYozOfPyz09i9lWwjYEwqBw1XM0yJ4cSohfIevZOruoJYhDEPkimOhxxDIwx4/eidsemNouf+jkTwANeya5pwgiXKCW3mWTVrmg9Esy8mYXk0fOYJgw/+uXKC+dlsKedfJJpQECDqnaGYp6enkVZHf6bhNXAhZ+UNlkohJKvLXj9+kArB2o2MI1P+97iLv9af5me0wJM/dBrJkJRP6B7sSbyIpUZAIbrVFBl66bEHM3w5Ws/pYOCOKDB3ITd9JezRxiKtdfCOEOZpEW6VdFLGX4369bS+eGCYe4U6HGM0KXtlXdl46cWQioIh4k7EoNphK5qW0WO5vyCkEDSqcrxiD1A09kc9qn6ayhp/0DHyWyhKWUluzweKQulGhvpveykGbBmzQNOSfop4pFjNlHy9N//1SDe/Opp8Si+MD3mg73tpaIv3bne0G0qPMot651owuPZN8pzjvLqUoup+54NgPwWrLxp1EEQQJT1yFeu7lpVDHiCIQG3Erksan6BNvHwXL1cPAgy7pTmd8=
    mysql-root-password: AgAA//HuSEfjQ6fe6E6GCIECXk8mfb0sZ3YFWX8cTQ3B2wMX3UEzKxnob2tfj3KwOdJ3mOG0Yy0oRYYlfC6V1Prz+3DtTGxKyCL1CcJGlo+RVkWhQfzhhxZTcE8mUIxM4lYxZ9oXTT28OY2eZqSS8KA6gvESbKBN9BnJfz8qrssU5vOZF9tsVRnj2opru8Xyq4ls8sV/qVa9aO2wfaKbYWslIXJ3wgUAA9NsN2F525jQh+OqH2YKLIHFqPjqrVTjtBFbiP7ZAKGRZ9i50Pob2w40jtBKFVwqBHcydbDz9uiWHFL+XGnKSO3bClSRDDjTy2P7C45F8sIjsck4nrgTaflpdgLn9H0o78onbmEgd8eJRRgUgyHpC34jnve2HMMD3D3sK3Vbqx1KVqm8Wsf2p8UOPVHk0fNBWLtvWDcu53KRErqbbv8PX7KvHQn8GHb+FyfUol9FnpLt9q9kMNbw5A6/v60nCdX9M6CyXc47DTFKBPA/vE77KnMwFAzsPu7Kdw0bI+zr5zj6XQFagFdKzVy0pln6UEUus26RHjLstXM4YPe+2cZRxUqzJNLcUPedsYiaprYM2RXD3iwJ19xKc1FbvjbfYfC499r+Y7RgwnUqynYj89kN7yaBUo3gYqqoHYZvHtB8d4fe3keeoUcHPL3RLV22UPo4UGF9qcdWQwPIHyMaAHlTMXx48TKSjxCXNLlPaVdAu5BBjVOe2jVOFP2d+8XZJPMsaWk=
  template:
    metadata:
      creationTimestamp: null
      name: zepto-db-secret
      namespace: zepto
